name: create the docker image push to dockerhub and the on ec2 pull the updated image and restart again
on:
  push:
    branches:
      - "main"

jobs:
  BuildAndDeployment:
    name: DockerAndEc2
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: build and push the image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          tags: arpitblagan27/refnet:latest

      - name: check it is pushed or not
        run: docker pull arpitblagan27/refnet:latest

      - name: deploy on ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull arpitblagan27/refnet:latest
            sudo docker stop web-app || true
            sudo docker rm web-app || true
            sudo docker run -d --name web-app -p 5173:5173 arpitblagan27/refnet:latest
